### ISSUE TITLE
Field defaults list

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#108] opened 2022-07-27 22:58 UTC
From Maura in Slack

```Fields defaults list is huge, can we pare this down -- how does this interact with existing fields and do we/can we override default with our own?```

**Comment by summer-cook** [comment] 2022-07-27 23:16
@dl-maura we could also use a little bit more clarification on this one- could you possibly provide a screenshot or more specifics?

**Comment by dl-maura** [comment] 2022-07-28 00:34
Sure I'll get a screenshot and post it here! @VanessaVenti if you know what defaults you want kept if you could provide that information that would be great

**Comment by dl-maura** [comment] 2022-07-28 14:19
![Screen Shot 2022-07-28 at 10 18 03 AM](https://user-images.githubusercontent.com/61880785/181535537-6f074c42-1fa0-45f8-9501-f8dc7e3d5b61.png)

**Comment by dl-maura** [comment] 2022-07-28 14:50
One thing to note aside from list size is that Funding is in twice for some reason. @VanessaVenti if you could post here what you were hoping to see, that would be great

**Comment by VanessaVenti** [comment] 2022-07-28 15:26
Hi @summer-cook, @dl-maura, and @bkiahstroud - 

The fields that come by default in Spotlight 2.0 are:
Description	
Attribution	
Date
Exhibit Tags

And the fields we have in our metadata template are:
Additional Digital Items
Attribution
Attribution
Available To
Cite As
Classification
Collection
Container
Contents
Creation Date
Creator Contributor
Creators Contributors
Culture
Date
Description
Digital Format
Edition
Exhibit Tags
Extent
Finding Aid
Finding Aid Component
Genre
HOLLIS Record
In Collection
Language
Materials Techniques
Notes
Permalink dcp
Permalink ham
Place Of Origin
Places
Publisher
Record ID
Repository
Rights
Series
Style Period
Subjects

I see we have Attribution twice. My guess is we added it again because the default Attribution wasn't set up the way we needed it to be so we created it again. And then we kept Description, Date, Exhibit Tags and added all the others. I'll not 100% sure about that though, let me know if you need to know for sure.

Going forward, it looks like there are a lot more default fields in 3.0 (as seen in Maura's screenshot above). Since I don't know how these are set up (and it doesn't look like you can change their set up via the UI) I'm not sure if we can use the ones that overlap with ours or if we need to recreate them all. We could either have no fields by default (or just the ones Spotlight requires on the back end like Title which isn't even listed in the UI) and then we just use the template to create them every time. Or we could use the template fields as our defaults. This seems like a bigger conversation though and I would want to know the difference between the defaults vs adding them from a technical perspective and also consult our metadata analyst. Do let me know your thoughts and if we should meet to discuss before we are all on vacation!

**Comment by sephirothkod** [comment] 2022-07-28 16:05
Hi Vanessa,

Spotlight 3.0 still only has the 4 default fields and the fields that show up in the screenshot from Maura are the ones we have set up already to work with your OAIPMH gem so far. We were going to set the rest up but wanted to get feedback on the harvesting first. There seems to have been some kind of miscommunication around this and I apologize about that. Our intention from the start has been to use the template fields as the defaults and then each exhibit admin can choose the visibility of each field to suit their needs. If this still works for you let me know and we will continue with the current plan. If you prefer to have them created via template each time then we should have a discussion around that and how it should work (although I really would recommend not going this route as it is not the proper way to do this in spotlight).

Cheers!

**Comment by VanessaVenti** [comment] 2022-07-28 17:02
Hi @sephirothkod - thanks for explaining this, I didn't know that! Yes, that does sound better to set up our template fields as the default rather than me have to import the template every time! As long as you know how to set them up to work with our mapping file and which to set as multi-value, that sounds great. In that case then I'm guessing you can remove one of the Attributions from our current list. And if we are making changes, I would also rename the following:

- 'Permalink dcp' to 'Harvard Digital Collections'
- 'Permalink ham' to 'Harvard Art Museums'

(They'll need to be updated in the yaml as well.)

A few questions:
- I also add a Permalink that is specific to each exhibit and it sounds like I would still do that, yes?
- After I harvest I rename the following fields like so because they can't have a '/' in Solr, would I still do this as well?:
  - Creator Contributor to Creator/Contributor
  - Creators Contributors to Creators/Contributors
  - Materials Techniques to Materials/Techniques
- You'll notice we have Creator/Contributor both singular and plural, this is because we use one for faceting and one as free text. Is there is a better way to handle that?
- Finally, I occasionally add new fields to our template or add an exhibit specific field. What would the process be like for doing each of those? I'm guessing I would need a dev to add new ones to our default set up and the new field would show up under ALL existing and new exhibits, but records would need to be reharvested for the new field to be populated. And that I'd still be able to add exhibit specific fields myself via the UI. Are my assumptions on both of those correct?

**Comment by VanessaVenti** [comment] 2022-07-28 17:14
Also, I know we have fields that I can't see in the UI for the thumbnail and raw object. I'm not sure if there are others, but wanted to make sure those were one your radar as well. I also think it would helpful to be able to see them in the admin UI to see how they are populated, but not show them to end users.

**Comment by VanessaVenti** [comment] 2022-07-28 17:52
Sorry - just thought of one more thing! We have a handful of exhibits that have custom fields that don't have much if any overlap with the ones in the template. I'm guessing for those we would hide all the default fields and add exhibit specific fields. Just want to make sure that will work.

**Comment by sephirothkod** [comment] 2022-08-01 13:18
@VanessaVenti Sorry for the late reply on this. 

- Yes you can still add exhibit specific fields for your permalinks.

-  The field labels will all be set to reference a `en.yml` locale file so that we can set the label to whatever we want at any time and the solr field will not be affected. Those renames you requested shouldn't be an issue.

- I would avoid mixing free text into facet fields as that can end up creating a bad end user experience. Many times when free text is allowed in facet field you end up with duplicates that are slightly different. These fields also use slightly different types of solr fields so that they work better for facets. (free text: tesim, facets: ssim)

- Yes a dev would need to add a new default field (it's very easy to do), and exhibit specific fields can still be created via the UI. You are correct, a new default field would show across all exhibits once a re-harvest has been done.

- The thumbnail and object url fields are in as default fields and the visibility can be turned off via the admin dashboard, so they can be switched to publicly viewable while working on an exhibit and then switched to non-viewable until you need them again. As for making them only show for admin that is probably out of scope for this specific project.

- Yes you can hide all the default fields if you want via the admin dashboard, and make a whole new set of exhibit specific ones.

**Comment by VanessaVenti** [comment] 2022-08-09 19:47
@sephirothkod - Just catching up on this after being away on vacation last week. Thanks for answering all my questions, all sounds good!

**Comment by VanessaVenti** [comment] 2022-09-01 18:44
This is a duplicate of #136

**Closed by VanessaVenti** 2022-09-01 18:44 UTC
Labels: Metadata & Harvesting Epic, 3.0 Launch
