### ISSUE TITLE
Existing items don't get updated on re-harveset

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#133] opened 2022-08-09 23:55 UTC
## Summary

Re-harvesting items that have already been harvested will not update properly. If, since the last time the item was harvested, either a new field has been added or the data upstream in OAI has changed, neither will be saved when re-harvesting.

## Acceptance Criteria

- [ ] Items are updated upon re-harvest

## Testing Instructions

_Testing this is kind of difficult; changing the data in the OAI feed and/or adding a completely new field to Solr feels overkill. If possible, both of those options work, but the simplest way to verify the fix is by making sure existing items `updated_at` changes upon re-harvest._

1. Login as an admin 
2. Navigate to Exhibit Dashboard > Items > Add Items
3. Fill out the form. Make note of which Set you choose to harvest
4. Click "Add MODS Items" 
5. Navigate to Exhibit Dashboard. Verify harvest succeeds under "Recent item indexing activity" 
6. Repeat steps 2-5 to re-harvest. Make sure you use the same set 
7. Open a rails console 
8. Find one of the harvested items (e.g. `item = Spotlight::Resources::OaipmhUpload.find_by(external_id: "1-W437076_URN-3:HPREWARD:2961291")`
9. Validate that the item's `updated_at` is different from its `created_at`

**Comment by bkiahstroud** [comment] 2022-08-12 18:34
PR: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/22

**Comment by VanessaVenti** [comment] 2022-08-24 14:45
@dl-maura and @phil-plencner-hl can you test this one by editing the metadata for an item in Solr and then reharvesting the item to make sure it updated. I don't have a way to test this without editing the original catalog record which doesn't seem like a good idea.

**Comment by dl-maura** [comment] 2022-08-24 14:50
I may need to work with @bkiahstroud to do this on QA, you actually may need to edit it outside the solr record because I think the re-harvest would just overwrite the record (when we tested on local we had to actually edit the harvest code to force an update). I will check though, if we have some QA collections with broken thumbnails I believe the reharvest shows an updated date.

**Comment by VanessaVenti** [comment] 2022-08-24 15:07
Oh yes, I'm pretty sure I was able to successfully reharvest a collection with broken thumbnails and then they appeared. I did run into the where reharvesting failed for another exhibit I created so I wasn't able to test it on that one. If you aren't able to easily test it on QA and think the thumbnails appearing is a sufficient test I'm fine with closing this one.

**Comment by dl-maura** [comment] 2022-09-01 14:52
We've confirmed a few times that this appears to be working, so closing this

**Closed by dl-maura** 2022-09-01 14:52 UTC
Labels: bug, Metadata & Harvesting Epic, 3.0 Launch
