### ISSUE TITLE
Missing metadata fields

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#110] opened 2022-07-27 23:03 UTC
# Summary
There are several metadata fields that still need to be added for the app to match up with their yml file

[From Maura & Phil in Slack](https://assaydepot.slack.com/archives/C02LLJDGQ9Z/p1658955524969019)
```Some of our metadata fields aren't coming in even after we created custom fields, is this expected? Tested with Materials Techniques```

example- they tried to add a field that they know existed on some items, and it was still not showing up
![Image](https://user-images.githubusercontent.com/73361970/181387259-d3f07f3a-0598-454e-a8b7-166230088a30.jpg)

# Acceptance criteria
- [ ] All metadata fields from [curiosity.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/curiosity.yml ) show in the UI

**Comment by VanessaVenti** [comment] 2022-09-01 18:43
This is a duplicate of #136

**Closed by VanessaVenti** 2022-09-01 18:43 UTC
Labels: Metadata & Harvesting Epic, 3.0 Launch
