### ISSUE TITLE
Conflicting fields cause metadata not to render in UI

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#155] opened 2022-08-22 14:20 UTC
Posted the demo video in slack, when harvesting contagion, we found a set of items is coming in broken.

Link to working item in prod: https://curiosity.lib.harvard.edu/contagion/catalog/36-W384604_urn-3:HMSCOUNT:1270061

To recreate, harvest the contagion set locally or in staging.

**Comment by bkiahstroud** [comment] 2022-08-22 23:31
Demo video: https://drive.google.com/file/d/1MR9uYpZg7bse3tcwgROEyR50DsIcw2DR/view

**Comment by bkiahstroud** [comment] 2022-08-22 23:48
Initial investigation points to this being caused by exhibit-specific fields conflicting with default fields. 

1. Import "demo" exhibit data 
2. Harvest "demo" set 
3. See "Language" doesn't render on item show pages 
4. Delete "Language" exhibit-specific field 
5. See "Language" renders successfully on item show pages

**Comment by bkiahstroud** [comment] 2022-08-23 23:46
MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/141

**Comment by summer-cook** [comment] 2022-08-29 23:36
Started to QA this, am still waiting for the contagion harvest to complete: https://staging-harvard-curiosity.notch8.cloud/summer-contagion/dashboard

**Comment by summer-cook** [comment] 2022-08-30 15:04
@bkiahstroud  are you sure this is on staging?

I just tried to QA this and it seems like many of the metadata fields are still not rendering in the UI on staging.
These are the steps i took

Create new exhibit
Harvest contagion
Look at an item compared to the same item in HDC (should have the same metadata)

[I am looking at the metadata fields in the UI](https://staging-harvard-curiosity.notch8.cloud/summer-contagion/metadata_configuration/edit) and there don't seem to be any duplicates which is good, but it seems we are still missing metadata on the show page. 

Example:
[Link to an item on staging](https://staging-harvard-curiosity.notch8.cloud/summer-contagion/catalog/16-990001337120203941)
[Link to the same item in Harvard Digital Collections ](https://digitalcollections.library.harvard.edu/catalog/990001337120203941)(it has a lot more metadata fields)

**Comment by summer-cook** [comment] 2022-08-31 22:54
@bkiahstroud I just checked this again and it seems like there are still missing metadata fields in the UI

**Comment by bkiahstroud** [comment] 2022-09-02 22:10
@summer-cook in retrospect, I think this was because we were harvesting with the wrong mapping file. 

I harvested demo on staging using the [curiosity.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/curiosity.yml) files and saw the metadata fields showing up as expected.

**Comment by VanessaVenti** [comment] 2022-09-12 21:03
To me, this looks like it will be fixed when #136 and #170 are working. I'm not sure if there is anything to test separately here. @bkiahstroud do you agree?

**Comment by bkiahstroud** [comment] 2022-09-13 16:29
Closing this in favor or tracking it on #136

**Closed by bkiahstroud** 2022-09-13 16:29 UTC
Labels: 3.0 Launch
